### ISSUE TITLE
No module named 'histogram'

### ISSUE THREAD

**Issue by mo10** [carsonfarmer/streamhist#1]
Hi, 
I found a problem when I was using it.
```
>>> from streamhist import StreamHist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/streamhist/__init__.py", line 9, in <module>
    from histogram import StreamHist
ModuleNotFoundError: No module named 'histogram'
```
I tried to install ,But I got `No matching distribution found for histogram`.
I found this package on pypi([histogram](https://pypi.python.org/pypi/histogram)), but I can't download it, returned 404.

How to solve this problem?

Thank you!

**Comment by carsonfarmer** [comment]
Hi @mo10. Are you trying to install streamhist using Python 3.X? I think this is a bug. I'm going to create a ticket for it to get it fixed. `histogram` is an internal module, so you can't install it separately. I'll try to get a fix to you soon. In the mean time, if you just git clone this repo and import the modules directly, it should get you up and going for now...

**Comment by mo10** [comment]
Thank you for the reply @carsonfarmer ,
I'm trying to use [predicure](https://github.com/carsonfarmer/predicure#features)
```
from predicure import SemiMarkov
import random
```
Then I got this problem.
I'm using `Python 3.6.4`. Should I use `Python2.x` to run it?

Thank you!

**Comment by carsonfarmer** [comment]
@mo10 what is the error you are getting with `predicure`? Also, its probably better to discuss issues you are having with that package over in that repo :)
