### ISSUE TITLE
Alternative implementation

### ISSUE THREAD

**Issue by MainRo** [carsonfarmer/streamhist#12]
Hello,
Since it seems that this repository is not maintained anymore, and I need such a library, I made another implementation. It is available on pypi and is also hosted on github:
https://github.com/maki-nage/distogram

This may interest other people looking for a python implementation of this algorithm.

**Comment by carsonfarmer** [comment]
Thanks @MainRo! I'll add this to the main README.

**Comment by carsonfarmer** [comment]
If you borrowed code or implementation details from this project/repo, I wuld certainly appreciate a link, reference, or notice in your license...

**Comment by MainRo** [comment]
Thanks for the link in the readme.
I did the implementation by following the paper (plus optimizations for the update function), but since I also read your code, I probably somehow reused some parts. So I added a credit section in my readme with a link to this repo.

**Comment by carsonfarmer** [comment]
`streamhist` is now also available on PyPi: https://pypi.org/project/streamhist/. Better late than never?
