### ISSUE TITLE
sum() is not monotonically increasing

### ISSUE THREAD

**Issue by lkorycki** [carsonfarmer/streamhist#13]
Hey Carson!

Unfortunately, I noticed that the current version of your library has some serious bug in the `sum()` function. Running your examples leads (soon or later) to the following result:

![hist1](https://user-images.githubusercontent.com/14258757/109834058-cbc57080-7c0f-11eb-82d8-35df64a7e1e5.png)

I've dug a little bit into it and, most likely, this is the commit that causes it: https://github.com/carsonfarmer/streamhist/commit/a9375074959d3b2e5b8db9c2559bce92a2649253

I know that @belm0 wrote it to fix the function and quantiles, but it looks like tests do not cover everything needed.

On the other hand, using an earlier version, e.g. https://github.com/carsonfarmer/streamhist/commit/7dc5169b1a6d48765e51f3806731ee36be9f1f5a, leads to: 

`u = (bin_i.value + (bin_i1.value - bin_i.value) * z) ->
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'`

in `_compute_quantile()`. So it's something that @belm0 probably fixed, but it turns out that there was a price for it ;) I know that you don't actively support the repository, but I think it's important for everyone to be aware of the problem.

**Comment by belm0** [comment]
Hello-- would you mind describing the bug and expected behavior rather than just citing a graph?  An issue summary other than "bug" would also be helpful.

**Comment by lkorycki** [comment]
Hey John! There is not much more that I can add to it, but let me try to be more specific.

To reproduce the problem, try to run the following script.


```
from streamhist import StreamHist

normal_data = np.random.normal(0.0, 1.0, 1000)
plt.hist(normal_data)

h1 = StreamHist(maxbins=8)
h1.update(normal_data)
print(h1.bins)

l, u = h1.bounds()
x = np.linspace(l, u, 10)
y1 = [h1.sum(z) for z in x]
print(y1)

y2 = [h1.density(z) for z in x]
plt.plot(x, y1, label="Sum")
plt.plot(x, y2, label="Density")
plt.title("Sum and density")
plt.ylabel("Frequency")
plt.xlabel("Data")
plt.legend(loc="best")
plt.show()
```
You should get plots for density and distribution function, as well as a histogram created based on the generated data. You may try to run it more than once to get the wrong result (2-3 attempts are usually enough).

![hist2](https://user-images.githubusercontent.com/14258757/109907163-c566e100-7c6f-11eb-8928-1a6f0d2f7e5c.png)

The result of the `sum()` function should be monotonically increasing for `y1 = [h1.sum(z) for z in x]`. Obviously, it is impossible for it to look like that. If we look into the printed variables we will see that:

1) bins are ok: `SortedKeyList([Bin(value=-2, count=5), Bin(value=-1, count=38), Bin(value=-1, count=102), Bin(value=0, count=198), Bin(value=0, count=303), Bin(value=0, count=193), Bin(value=1, count=132), Bin(value=2, count=29)]`

2) sums are not: `[971.0, 11.89648068360107, 55.19992544741399, 163.30276154161226, 352.8619555943503, 605.8320984126633, 796.2967144457533, 922.8081592060216, 985.1754344606137, 1000.0]`

So I assume there is something wrong with the `sum()` function, the values in 2) should be increasing.

Let me know if you can reproduce this error and if you need anything else.

**Comment by belm0** [comment]
Thank you-- please change title to `sum() is not monotonically increasing` if you have a chance.  (I don't have permission.)

**Comment by lkorycki** [comment]
Sure thing, done.

**Comment by belm0** [comment]
The bug is here.  When `i` is -1, then `prev_sum` is incorrectly aggregating the count of all bins except the last one.  Rather it should be initialized to 0.

https://github.com/carsonfarmer/streamhist/blob/3a46bf82e2bb2b5124409319d93b5d1f97a7781e/streamhist/histogram.py#L345-L348

**Comment by lkorycki** [comment]
Yeah, the negative index definitely explains that. Can you fix it?

**Comment by belm0** [comment]
Yes, I'll make a pull request.  But I couldn't say when it would be merged.

Though have you considered https://github.com/maki-nage/distogram, which is significantly faster and available in pypi?

**Comment by carsonfarmer** [comment]
While distogram is indeed faster... they are both now available on PyPi: https://pypi.org/project/streamhist/

Better late than never?

**Comment by lkorycki** [comment]
Thank you guys!
