### ISSUE TITLE
Weighted Histogram

### ISSUE THREAD

**Issue by rzu512** [carsonfarmer/streamhist#2]
Can I add weighted data such as tuple of (value, weight) to the histogram?

**Comment by carsonfarmer** [comment]
You bet! The `update` method takes an optional `count` argument which defaults to 1, but can be any non-negative integer. I _think_ it'll work with floats as well, though that hasn't been tested.
So if you have a (value, weight) tuple, you can use:

```python
hist.update(value, weight)
# or...
pair = (value, weight)
hist.update(*pair)
```
